---

- name: kolla-ansible bootstrap-servers inside /root/project/virtualenv
  command: "/root/project/virtualenv/exec /root/kolla-ansible/tools/kolla-ansible -i /root/multinode bootstrap-servers"

- include: registry.yml

- name: kolla-genpwd inside /root/project/virtualenv
  command: "/root/project/virtualenv/exec /root/kolla-ansible/tools/generate_passwords.py"
- name: kolla-ansible prechecks inside /root/project/virtualenv
  command: "/root/project/virtualenv/exec /root/kolla-ansible/tools/kolla-ansible -i /root/multinode prechecks"
- name: kolla-ansible pull inside /root/project/virtualenv
  command: "/root/project/virtualenv/exec /root/kolla-ansible/tools/kolla-ansible -i /root/multinode pull"

# Pause for 5 minutes to build app cache.
- pause:
    minutes: 5

# The following line is erroring out, but seems to work when run manaully.
- name: kolla-ansible deploy inside /root/project/virtualenv
  command: "/root/project/virtualenv/exec /root/kolla-ansible/tools/kolla-ansible -i /root/multinode deploy"