---

- name: Add mappings to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item.ip }} {{ item.fqdn }} {{ item.name }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  with_items:
    - { name: centos7node1, ip: 10.100.194.21, fqdn: centos7node1.cs.siu.edu }
    - { name: centos7node2, ip: 10.100.194.22, fqdn: centos7node2.cs.siu.edu }
    - { name: centos7ceph1, ip: 10.100.194.23, fqdn: centos7ceph1.cs.siu.edu }
    - { name: centos7ceph2, ip: 10.100.194.24, fqdn: centos7ceph2.cs.siu.edu }
    - { name: centos7ceph3, ip: 10.100.194.25, fqdn: centos7ceph3.cs.siu.edu }