---

- name: Install ntp
  package: name=ntp state=present

- name: disable chronyd
  systemd:
    name: chronyd
    state: stopped
    enabled: no

- name: enable ntpd
  systemd:
    name: ntpd
    state: started
    enabled: yes

- name: Configure hard disks for external_ceph
  include: prepdisks.yml
  when: external_ceph | bool

- name: Configure hard disks for internal ceph
  include: no-ext-ceph-prepdisks.yml
  when: not external_ceph | bool

# External Ceph
#- include: prepdisks.yml
# No external Ceph, skip line above
#- include: no-ext-ceph-prepdisks.yml
